### ISSUE TITLE
I have tried to written the implementation for the phi2 model. However, I am experiencing some problems:

### ISSUE THREAD

**Issue by GiacomoLeoneMaria** [schwartz-lab-NLP/TOVA#4]
I have tried to written the implementation for the phi2 model. However, I am experiencing some problems:

* doing a test on the model with and without tova, it turns out that tova consumes more VRAM 

i don't understand where the error is in my implementation in custom_phi.py or what i am not considering or doing wrong.

can you help me 

_Originally posted by @GiacomoLeoneMaria in https://github.com/schwartz-lab-NLP/TOVA/pull/3_

**Comment by hassidm** [comment]
Hi,

Thanks for reaching out!

It seems that your implementation is missing a call to the "reduce()" function. As an example, you can refer to the implementation for llama in:
https://github.com/schwartz-lab-NLP/TOVA/blob/59be3d17a5f3327b99c67c3b9f78bae96f9563b8/src/convert_models/llama_custom.py#L112

Can you try again with an updated implementation?

Hope it helps :)
